### ISSUE TITLE
Can't restart FIREFOX process !!!

### ISSUE THREAD

**Issue by talal2** [winsiderss/systeminformer#1659] opened 2023-03-23 19:50 UTC
When i try to restart firefox, i got this: 
![image](https://user-images.githubusercontent.com/29613653/227334896-17eb32e8-97d8-4062-8318-5d56550f5515.png)
I'm on windows 11 X64 !!!
P.S: The client is executed as ADMIN .

                                   Thanks in advance !

**Comment by dmex** [comment] 2023-03-24 04:33
Duplicate of #1621

**Closed by dmex** 2023-03-24 04:33 UTC
