### ISSUE TITLE
RAPL Devices 5900x Unknown Device

### ISSUE THREAD

**Issue by navjack** [winsiderss/systeminformer#1989] opened 2024-02-24 16:50 UTC
### Brief description of your issue

![5900x an unknown device for RAPL](https://github.com/winsiderss/systeminformer/assets/7362750/f0759f39-f2b4-4311-ba08-1012aa49b081)

I've noticed that the options menu has said this about my 5900X for quite a while now. I don't really think anything of it but just from the UX standpoint it is always alarming to see that [UNKNOWN DEVICE - PLEASE REPORT ON GITHUB] message next to all my enumerated CPUs.

Is it supposed to be like this or we eventually get access in this wonderful program the ability to see the RAPL counters?

### Environment (optional)

* System Informer 3.0.7459
* Windows 11 Pro for Workstations Insider Preview 26040.rs_prerelease
* Any other information that could possibly be helpful I'd be glad to give

**Comment by dmex** [comment] 2024-02-24 23:57
Duplicate of #1558

> Is it supposed to be like this or we eventually get access in this wonderful program the ability to see the RAPL counters?

Microsoft aggregate Intel devices into single objects but they haven't done the same with AMD and since RAPL is new I've been waiting to see if they update the driver with the next Win11 release.

**Closed by dmex** 2024-02-24 23:57 UTC
Labels: bug, needs investigation
