### ISSUE TITLE
Translation of the software interface

### ISSUE THREAD

**Issue by phpll-cyber** [winsiderss/systeminformer#1578] opened 2023-01-26 12:24 UTC
### Description of the feature, modification, idea or suggestion

Translation of the software interface in other languages

### Proposed implementation details (optional)

I want to translate the software
I just need help knowing how to translate
Thank you

**Comment by jxy-s** [comment] 2023-01-29 00:33
Duplicate of: https://github.com/winsiderss/systeminformer/issues/302

**Closed by jxy-s** 2023-01-29 00:33 UTC
Labels: enhancement
