### ISSUE TITLE
3.1.24258 Nightly Crashing on systems with Xeon V2 CPU's

### ISSUE THREAD

**Issue by DavidXanatos** [winsiderss/systeminformer#2218] opened 2024-09-26 14:34 UTC
### Brief description of your issue

The current build (3.1.24258) of System Informer Nightly crashes on systems with Xeon V2 CPUs. The application fails to start, triggering WerFault.exe. The crash occurs at the instruction vpbroadcastw xmm2,xmm2, which appears to be an AVX2 instruction.

Please consider avoiding the requirement for AVX2, as it's unnecessary overkill for this application. SSE 4.2 should be sufficient, and requiring more advanced instruction sets than Windows 11 is not ideal.

### Steps to reproduce (optional)

Run latest SI nightly on a system with a Xeon V2 CPU

### Expected behavior (optional)

Not crashing

### Actual behavior (optional)

```Exception thrown at 0x00007FF6D34F8EA0 in SystemInformer.exe: 0xC000001D: Illegal Instruction.```

### Environment (optional)

Windows Server 2019 on Dual Xeon V2

**Comment by dmex** [comment] 2024-09-26 22:00
Duplicate of #2201

**Closed by dmex** 2024-09-26 22:00 UTC
Labels: needs-triage
