### ISSUE TITLE
Access to the kernel driver is restricted

### ISSUE THREAD

**Issue by Serega124** [winsiderss/systeminformer#1873] opened 2023-10-14 08:20 UTC
### Brief description of your issue

Unable to load the kernel driver

### Steps to reproduce (optional)

1. Fresh install System Informer
2. Run
3. Go to Settings - check Enable kernel-mode driver
4. Restart System Informer

### Expected behavior (optional)

Kernel driver should be loaded

### Actual behavior (optional)

An error appears:
![image](https://github.com/winsiderss/systeminformer/assets/5006548/034e6b5d-d1f1-4339-b9b3-fcae3d993351)
```
[Window Title]
System Informer

[Main Instruction]
Access to the kernel driver is restricted.

[Content]
    - not securely created
    - inactive protections

You will be unable to use more advanced features, view details about system processes or terminate malicious software.

[ ] Don't show this message again  [OK]
```

### Environment (optional)

```shell
System Informer 3.0.7270 (d44e4d0)
Windows 10.0.19045.3570
```

**Comment by Serega124** [comment] 2023-10-14 09:01
rolled back to 3.0.6806 and it works fine:
![image](https://github.com/winsiderss/systeminformer/assets/5006548/136a00a9-4b4f-4ad0-bd38-919840d9d828)

**Comment by jxy-s** [comment] 2023-10-14 16:13
@Serega124 I'm unable to reproduce this. Would you please gather a trace log? Follow these instructions:

1. open an elevated command prompt
2. execute: `logman create trace ksi -p {F64B58A2-8214-4037-8C7D-B96CE6098F3D} 0xffffffff 0xff -bs 64 -nb 16 128 -o "kph.etl" -v mmddhhmm -ow`
3. execute: `logman start ksi`
4. reproduce the issue
5. execute: `logman stop ksi`
6. execute: `logman delete -n ksi`
7. harvest the `kph_nnnnnnnn.etl` trace log from disk
8. attach the log file here or email it to me (johnny.shaw@live.com)

**Comment by Serega124** [comment] 2023-10-14 17:03
[kph_10141950.zip](https://github.com/winsiderss/systeminformer/files/12907016/kph_10141950.zip)

**Comment by jxy-s** [comment] 2023-10-14 18:04
```
KphVerifyFile: 7072 "\Device\HarddiskVolume8\Program Files\SystemInformer\SystemInformer.exe": STATUS_SUCCESS (0x00000000)
Started protecting process 7072
...
KphGuardGrantSuppressedCallAccess failed (0x00000001, 0x00000001): STATUS_ACCESS_DENIED (0xC0000022)
KphCheckProcessApcNoopRoutine failed: STATUS_ACCESS_DENIED (0xC0000022)
Stopped protecting process 7072
```

@Serega124 this is a duplicate of https://github.com/winsiderss/systeminformer/issues/1833 - the fix on master but we haven't done another driver release for it. The workaround for now is to disable ACG for SystemInformer.

![image](https://github.com/winsiderss/systeminformer/assets/11687482/70e8a446-17dd-43b9-ba23-aec6cd6719fb)

**Closed** 2023-10-14 18:04 UTC
Labels: bug, needs investigation

**Comment by MagicAndre1981** [comment] 2026-05-05 19:48
I also get this now since last Update to [4.0.26125.1736](https://github.com/winsiderss/si-builds/releases/tag/4.0.26125.1736)

<img width="512" height="412" alt="Image" src="https://github.com/user-attachments/assets/e985e810-03d4-4ed5-a138-f56cd1260763" />

Older version [4.0.26125.851](https://github.com/winsiderss/si-builds/releases/tag/4.0.26125.851) worked fine. Rebooting and disabling ACG also doesn't fix it.

Any ideas? @jxy-s 

// Edit: I made the rollback to 4.0.26125.851 and everything works fine again.

**Comment by jxy-s** [comment] 2026-05-05 23:15
@MagicAndre1981 our CI failed to sign some of the binaries - we are investigating.
