### ISSUE TITLE
Unknown Device for AMD Ryzen 7 PRO 78401U w/ Radeon 780M Graphics

### ISSUE THREAD

**Issue by FelixIsaac** [winsiderss/systeminformer#2307] opened 2024-11-30 21:41 UTC
### Brief description of your issue

Going to the System Informer options, RAPL Devices, I see the following screen where the message "UNKNOWN DEVICE - PLEASE REPCRT ON GITHUB]", and hence I'm here reporting it :)

![image](https://github.com/user-attachments/assets/bffd57a8-561b-451e-a401-e0bae65d353e)

### Steps to reproduce (optional)

With **AMD Ryzen 7 PRO 78401U w/ Radeon 780M Graphics** integrated GPU:
> System Informer > Options > RAPL Devices

### Environment (optional)

```shell
Windows version: Windows 11 23H210.02631
Kernel version: Windows Kernel 10.02621.4455
System Informer version: 3.124298.0 Release 00-8664-d17ee503-01047000
CPU with Integrated-GPU: AMD Ryzen 7 PRO 78401U w/ Radeon 780M Graphics
```

**Comment by dmex** [comment] 2024-11-30 22:52
Duplicate of #1558

**Closed by dmex** 2024-11-30 22:52 UTC
