### ISSUE TITLE
Can not suspend some steamwebhelper.exe processes

### ISSUE THREAD

**Issue by DavidXanatos** [winsiderss/systeminformer#1915] opened 2023-11-29 07:04 UTC
### Brief description of your issue

When using SI to suspend steamwebhelper.exe of the usual around 6 processes 1 or 2 never suspend, inspecting the threads shows that all but 2 threads got suspended, sand 2 threads can not be suspended even when trying to directly suspend them from the thread list view.

This issue has been observed on windows 10 and has been reproduced on windows 11 there I tried also the new Freeze option which also failed.

### Steps to reproduce (optional)

1. Install Steam (the game launcher form valve https://store.steampowered.com/about/)
2. run steam
3. use System Informer to suspend all steamwebhelper.exe processes
4. observe that 1 or 2 of them stubbornly refuse to get fully suspended.

### Expected behavior (optional)

suspend should work

### Actual behavior (optional)

suspend leaves 1-2 threads unsuspended

### Environment (optional)

```shell
systeminformer-3.0.7333
windows 10 and 11
```

**Comment by dmex** [comment] 2023-11-29 10:34
Duplicate of #856

**Closed by dmex** 2023-11-29 10:34 UTC
