### ISSUE TITLE
GeoLite database update broken in systeminformer-3.1.7741-canary-bin

### ISSUE THREAD

**Issue by Almighty188** [winsiderss/systeminformer#2088] opened 2024-06-08 00:56 UTC
### Brief description of your issue

It appears GeoLite database update is broken in systeminformer-3.1.7741-canary-bin but works correctly in
systeminformer-3.0.7660-canary-bin using SystemInformer.exe.settings.xml with the exact same contents

### Steps to reproduce (optional)

1) Run amd64\SystemInformer.exe as admin
2) Then either Tools, Network Tools,  GeoLite database update... or System, NetworkTools, Download Update
    where the MaxMind GeoLite License Key is already filled out.

### Expected behavior (optional)

It is supposed to update like systeminformer-3.0.7660-canary-bin immediately after systeminformer-3.1.7741-canary-bin failed:
<img width="897" alt="image" src="https://github.com/winsiderss/systeminformer/assets/78993393/2e326920-8e8f-4e36-bc07-ce395e384064">

### Actual behavior (optional)

systeminformer-3.1.7741-canary-bin shows:
![image](https://github.com/winsiderss/systeminformer/assets/78993393/a6df5358-75d9-4b47-a59e-bdec68025849)

systeminformer-3.0.7660-canary-bin works correctly after I quit systeminformer-3.1.7741-canary-bin as mentioned in expected behavior with:
<img width="897" alt="image" src="https://github.com/winsiderss/systeminformer/assets/78993393/9be2b054-4d83-493e-a47f-8945848f156f">

### Environment (optional)

```shell
System Informer version 3.1.7741-canary-bin
Windows Insider Beta Build 22635.3720 (23H2)
```

**Comment by Almighty188** [comment] 2024-06-08 03:04
I found the issue, the error message says it needs either the GeoLite ID or Key but in reality, it needs both the GeoLite ID and Key.
<img width="1072" alt="image" src="https://github.com/winsiderss/systeminformer/assets/78993393/69c77d56-2ec6-4f02-902a-dfb8f010c564">

I know only the key works in the older version of systeminformer as mentioned earlier.  Just entering the GeoLite ID without the key does not work as systeminformer will complain about the License key being required.

**Comment by dmex** [comment] 2024-06-08 17:48
Changes to MaxMind License Keys: https://dev.maxmind.com/geoip/release-notes/2023#changes-to-maxmind-license-keys

Duplicate of #2069

**Closed by dmex** 2024-06-08 17:48 UTC

**Comment by Almighty188** [comment] 2024-06-08 17:53
> Changes to MaxMind License Keys: https://dev.maxmind.com/geoip/release-notes/2023#changes-to-maxmind-license-keys
> 
> Duplicate of #2069

Not exactly a duplicate as there are no problems with the key in 3.0.7660.   The bug is that if you look at the error message, it says ID *or* key, not ID *and* key.
