### ISSUE TITLE
Add winget support for processhacker

### ISSUE THREAD

**Issue by RichardJECooke** [winsiderss/systeminformer#1571] opened 2023-01-23 07:14 UTC
### Description of the feature, modification, idea or suggestion

Just discovered this app and it seems great. It would be nice to be able to automate the install like most other Windows apps with `winget install processhacker` though. Please add it to the repo.

**Comment by Masamune3210** [comment] 2023-01-23 11:38
Couldn't even if they wanted to. There is a standing issue report about this failure to get added due to Defender detecting it as malicious. Haven't tried since a bit after the rename and rework, but once it becomes a normal release it could be attempted to get it added again. I would wait until then though

**Comment by dmex** [comment] 2023-01-23 13:11
Duplicate of #620

> There is a standing issue report about this failure to get added due to Defender detecting it as malicious

Defender itself and WDSI submissions were not flagging the binaries as malicious or even PUA... Microsoft have a secondary blocklist of software they don't want available via the Store and this secret blocklist doesn't have a dispute mechanism. 

This is why the submissions were running for 72 hours and failing without error messages and the winget developers were not able to do anything about the submission. You can contact WDSI to resolve malicious detections but they couldn't do anything either because Defender was reporting the binaries as clean.

**Closed by dmex** 2023-01-23 13:11 UTC
Labels: enhancement
