### ISSUE TITLE
Windows Kernel Support: Windows 11 23H2 10.0.22631

### ISSUE THREAD

**Issue by IgorKorkin** [winsiderss/systeminformer#2119] opened 2024-06-29 18:55 UTC
### Brief description of your issue

Hi all! 
Please add support for the following Windows kernel version:

- Windows 11 23H2 10.0.22631
- Windows Kernel 10.0.22621.3810
- System Informer 3.0.7660 (`08de40d`)

Thank you a lot! 

![image](https://github.com/winsiderss/systeminformer/assets/10939751/523d6a56-e094-44b4-93e8-631a8535b1cd)

**Comment by dmex** [comment] 2024-06-30 04:00
Duplicate of #1823

**Closed by dmex** 2024-06-30 04:00 UTC
Labels: bug, needs investigation
