### ISSUE TITLE
RAPL unknown device

### ISSUE THREAD

**Issue by gmit3** [winsiderss/systeminformer#2270] opened 2024-11-04 19:45 UTC
### Brief description of your issue

I see "UNKNOWN DEVICE - PLEASE REPORT ON GITHUB" for my 5965WX CPU. Can I help somehow to get it supported?

**Comment by dmex** [comment] 2024-11-04 20:30
Duplicate of #1558 

>  Can I help somehow to get it supported?

Soon ™️

**Closed by dmex** 2024-11-04 20:30 UTC
Labels: needs-triage
