### ISSUE TITLE
PE Viewer crash (0xC0000005)

### ISSUE THREAD

**Issue by rxznve** [winsiderss/systeminformer#1812] opened 2023-08-15 05:19 UTC
### PE Viewer crash (0xC0000005)

PE Viewer crashes when opening the library exports table.

### Steps to reproduce (optional)

Create a library with the following exported functions (.def file in Visual Studio IDE)

```
LIBRARY TESTLIB
EXPORTS
  Test @123
  Test2 @456
  Test3 @789
  Test4 @1000
  Test5 @7
  Test6 @666
```
Compile. When you open the library exports table in PE viewer, you will receive a message **invalid access to memory allocation**. The library is **working** and in **x64dbg** everything is displayed **correctly**.

**Comment by dmex** [comment] 2023-08-15 21:53
> Create a library

Static library or DLL?

![image](https://github.com/winsiderss/systeminformer/assets/1306177/4b1d3cd1-d03b-4fc3-b815-8650133b4fb2)

**Comment by rxznve** [comment] 2023-08-15 23:50
> > Create a library
> 
> Static library or DLL?
> 
> ![image](https://user-images.githubusercontent.com/1306177/260850538-4b1d3cd1-d03b-4fc3-b815-8650133b4fb2.png)

Dll

**Comment by dmex** [comment] 2023-12-26 22:02
Unable to reproduce with nightly builds

**Comment by jxy-s** [comment] 2024-02-10 21:50
I suspect this is related to this issue: https://github.com/winsiderss/systeminformer/issues/1907

I am also unable to reproduce. But I intended to close this out when the next build publishes per the change above. If the issue persists after the next build please reopen the issue.

**Comment by jxy-s** [comment] 2024-02-14 06:07
`3.0.7459` - `Help > Check for updates` 👍

**Closed by jxy-s** 2024-02-14 06:07 UTC
Labels: needs more information, waiting on build
