### ISSUE TITLE
It does not support Chinese

### ISSUE THREAD

**Issue by linchen958** [winsiderss/systeminformer#2084] opened 2024-06-04 09:08 UTC
Due to the fact that this software does not support Chinese, I am unable to use it conveniently. I would greatly appreciate it if the developer could add Chinese support to the software so that I can use it conveniently. Thank you!

由于这款软件不支持中文，使我不能方便地使用此软件，我非常希望开发者给软件增加对中文的支持，以便我能方便地使用此软件，谢谢！

**Comment by dmex** [comment] 2024-06-17 10:12
Yep, tracking in #302

Duplicate of #302

**Closed by dmex** 2024-06-17 10:12 UTC
