### ISSUE TITLE
Dialog forms open in the background

### ISSUE THREAD

**Issue by maksimaliabyshev** [winsiderss/systeminformer#2344] opened 2024-12-24 08:32 UTC
### Brief description of your issue

Dialog forms open in the background, if View -> Always on top 

### Steps to reproduce (optional)

View -> Always on top  check on.
Double click any Service.

### Environment (optional)

```shell
System Informer 3.1.24333.0 Canary
Windows 11 23h2
```

**Comment by dmex** [comment] 2024-12-25 06:22
Duplicate of #200

**Closed by dmex** 2024-12-25 06:22 UTC
Labels: needs-triage
