### ISSUE TITLE
Unable to commit detours transaction message every time I open System Informer

### ISSUE THREAD

**Issue by Aholicknight** [winsiderss/systeminformer#1670] opened 2023-04-01 02:34 UTC
### Brief description of your issue

![5ZNxHx2bD](https://user-images.githubusercontent.com/7843719/229261566-dec8b416-7b72-408e-9801-bdc8c84157d2.png)

I get this message everytime I open System Informer, I do not know why this keeps popping up, but if I click "Close" the program still works fine.

### Steps to reproduce (optional)

I have no idea why this is popping up to begin with, so I don't know.

### Expected behavior (optional)

For this message to not show up at all

### Environment (optional)

```shell
System Informer Nightly
Version: 3.0.6433 (a6af28e)
```

**Comment by dmex** [comment] 2023-04-02 02:17
Duplicate of #1646

See https://github.com/winsiderss/systeminformer/issues/1646#issuecomment-1474079745

Execute: 
`REG DELETE "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SystemInformer.exe" /f`

**Closed by dmex** 2023-04-02 02:17 UTC
Labels: bug, needs investigation

**Comment by gggirlgeek** [comment] 2023-04-15 05:22
Thank you. I had this problem too.

**Comment by spetterman66** [comment] 2024-03-07 14:15
What a legend <3
