### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by mobamoba** [winsiderss/systeminformer#1956] opened 2024-01-06 13:18 UTC
### Brief description of your issue

There's a memory leak in System Informer where it uses more and more and more RAM over time and completely slows down my entire computer. For instance as I'm typing this, Private Bytes are at 8.28GB for System Informer and crawling up every minute or so. Yesterday I didn't notice until my computer was slow and I saw System Informer was eating 40 GB RAM. Terminating and restarting SI fixes it until it leaks again.

I'm happy to provide additional info as it's repeatable but am not sure what would help debug this. Thanks.

### Environment (optional)

```shell
3.0.7422
Windows 10
```

**Comment by TETYYS** [comment] 2024-01-11 10:50
Try disabling half of the plugins (and then the other half) to see if its a plugin that is causing it.

**Comment by MagicAndre1981** [comment] 2024-01-11 13:21
capture a [ETW trace (VAlloc/Heap) ](https://learn.microsoft.com/en-us/windows-hardware/test/wpt/memory-footprint-optimization-exercise-2#step-1-gather-a-virtualallocheap-trace-using-wpr) of the memory usage grow and analyze it in WPA.exe. In WPA.exe load the debug symbol from Symbol Server and from the [expanded PDB zip of System Informer](https://github.com/winsiderss/si-builds/tags). To do this, drag & drop the 'VirtualAlloc Commit Lifetimes’ graph from left side to the analyze pane and expand the "Commit Stack". Read the documentation from the link and follow the steps

**Comment by mobamoba** [comment] 2024-01-12 21:14
Disabling plugins didn't solve the problem (I disabled all of them, restarted SI, and still had the leak).

I was able to collect the data using the link provided and WPR but everytime I tried to open it in WPA, WPA crashed. So I have the ETL and other files but can't read it. I don't know if it contains any personal data but, if not, I'm happy to send it to someone else to see if they can get it to open.

**Comment by MagicAndre1981** [comment] 2024-01-13 13:28
zip the ETL, upload the zip to OneDrive and send the link to @jxy-s (he has his email in the profile)

**Comment by mobamoba** [comment] 2024-01-16 13:26
@jxy-s I sent to your listed email with a link to the zip and a clear subject line in case it winds up in your spam. Thanks.

**Comment by jxy-s** [comment] 2024-01-18 19:48
Thank you, I'll review when I find time.

**Comment by jxy-s** [comment] 2024-01-20 17:57
The leak is inside the device provider.
![image](https://github.com/winsiderss/systeminformer/assets/11687482/425c752c-c89d-4fe9-a9bc-7ed1b5a8a675)

I'm still working on identifying the root cause of the leak. In the meantime you can disable the device support (`Options > Advanced > EnableDeviceSupport > 0`).
![image](https://github.com/winsiderss/systeminformer/assets/11687482/6d807e29-cc66-41eb-a7d2-e753407f1db4)

**Comment by jxy-s** [comment] 2024-01-20 18:19
The `HDEVINFO` handle was being leaked. Each device item references this handle so it can independently query into the device information while the remainder of the tree may be dereferenced. The intention for this handle to remain referenced for things like the device properties dialog. However, while the reference to the device info handle was dereferenced for the tree object, it was not dereferenced for each device item in the tree. The fix is here (https://github.com/winsiderss/systeminformer/commit/9f440fe6de25ea59013eddaba2bc1c0bf7fb5615) and will be in the next build 👍 .

**Comment by jxy-s** [comment] 2024-01-24 03:36
Fixed in `3.0.7432`

**Closed by jxy-s** 2024-01-24 03:36 UTC
Labels: bug
