### ISSUE TITLE
Unable to load kernel driver

### ISSUE THREAD

**Issue by oguh43** [winsiderss/systeminformer#2329] opened 2024-12-12 10:15 UTC
### Brief description of your issue

<img width="404" alt="image" src="https://github.com/user-attachments/assets/acb2f60c-12c1-4ab2-85c9-0ef46be9150b" />

### Steps to reproduce (optional)

<img width="404" alt="image" src="https://github.com/user-attachments/assets/0562ba7b-6cc2-4395-9027-ccd35826e237" />

### Expected behavior (optional)

<img width="404" alt="image" src="https://github.com/user-attachments/assets/965f21ef-7d8a-4152-91a9-107ed31c648f" />

### Actual behavior (optional)

<img width="404" alt="image" src="https://github.com/user-attachments/assets/81d8b00b-d837-4c9d-8455-139bc4f42f77" />

**Comment by dmex** [comment] 2024-12-12 16:20
Duplicate of #1823

**Closed by dmex** 2024-12-12 16:20 UTC
