### ISSUE TITLE
Unknown Device - Please Report on GitHub

### ISSUE THREAD

**Issue by Healarybuf** [winsiderss/systeminformer#2043] opened 2024-04-30 02:54 UTC
### Description of the feature, modification, idea or suggestion

I receive the above message in the RAPL Devices settings.
![image](https://github.com/winsiderss/systeminformer/assets/81938961/96a92830-8951-413e-a41c-13bd1b574ae4)

That is all. :)

**Comment by dmex** [comment] 2024-05-01 23:49
Duplicate of #1558

**Closed by dmex** 2024-05-01 23:49 UTC
Labels: enhancement
