### ISSUE TITLE
Unable to load the following plugin: DotNetTools.dll

### ISSUE THREAD

**Issue by 0x79H** [winsiderss/systeminformer#1590] opened 2023-02-03 10:08 UTC
### Brief description of your issue

after update; SystemInformer version is 3.0.5958(5232c96) x64

```
[Window Title]
System Informer

[Main Instruction]
Unable to load the following plugin(s)

[Content]
DotNetTools.dll: %hs is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0x%08lx

[OK]
```
DotNetTools.dll
version: 3.0.0.0
CRC32: 6C74A3D6
MD5: D064FF9B1FC3C792CDF92B4FF02C2399
SHA-1: C0118D0F08F865B9CE4866FEC55995500CB0909F
SHA-256: 7C93C07334B4258865E926A2FC14CDFB8B900D7AAA5D3D492007D8553CC116F5

DotNetTools.sig is empty, file size is 0

info: I try to download https://github.com/winsiderss/si-builds/releases/download/3.0.5958/systeminformer-3.0.5958-bin.zip, only \systeminformer-3.0.5958-bin.zip\amd64\plugins\DotNetTools.sig is empty.

**Comment by Vasilich** [comment] 2023-02-03 20:28
happened with me also after today's update.
W10 22H2 x64

**Comment by pasha-zzz** [comment] 2023-02-04 00:45
Try this (maybe only sig-file needed):
[DotNetTools.zip](https://github.com/winsiderss/systeminformer/files/10593550/DotNetTools.zip)

**Comment by Biswa96** [comment] 2023-02-04 04:27
It seems that the latest 3.0.5958 version is re-released. Can anyone try with the new installer from here https://systeminformer.sourceforge.io/nightly.php ? The issue is fixed in my system.

**Comment by pasha-zzz** [comment] 2023-02-04 04:53
Yes installer was rebuilt 03 Feb ~19:00 UTC

**Comment by 0x79H** [comment] 2023-02-04 14:08
fixed

**Comment by Vasilich** [comment] 2023-02-04 19:10
Fix confirmed.
I have redownloaded latest zip file and replaced all changed files (all *.sig files) - now DotNetTools is loaded successfully.

**Comment by dmex** [comment] 2023-02-06 12:50
> redownloaded latest zip file and replaced all changed files
> Fix confirmed.

That's a workaround not a solution 😉

> DotNetTools.sig is empty, file size is 0

This should have failed the build but it ran successfully which was strange. There might have been a race between the build and the signing. I've added extra error handling to check for 0-byte signature files so we don't release builds without signatures 👍

**Closed by dmex** 2023-02-06 12:50 UTC
Labels: bug, needs investigation
