### ISSUE TITLE
Hide system processes

### ISSUE THREAD

**Issue by wincmd64** [winsiderss/systeminformer#1640] opened 2023-03-11 08:27 UTC
### Brief description of your issue

win7 - work
win10 - doesn't work
v3.0.10822.6295
![2023-03-11 09_47_57-System Informer  KRASNOVA_admin  (Administrator)](https://user-images.githubusercontent.com/104612222/224473874-4b155a58-7b35-4814-ab69-2d6501bbf143.png)
![2023-03-11 10_24_45-742 809 099 - AnyDesk](https://user-images.githubusercontent.com/104612222/224473878-9a0be967-c51d-4a6d-a285-6e5d7c5d31bb.png)

**Comment by dmex** [comment] 2023-04-24 09:44
Duplicate of #1604

**Closed by dmex** 2023-04-24 09:44 UTC
