### ISSUE TITLE
All settings suddenly got reset.

### ISSUE THREAD

**Issue by Dajova** [winsiderss/systeminformer#2195] opened 2024-09-11 19:07 UTC
My settings was fine earlier today, but after a reboot i did just now, all my SI settings where for some reason reset back to default. Is there a reason for this and/or is there a way to recover them?

**Comment by dmex** [comment] 2024-09-17 01:52
Have you used any system tweaking tools and modified the OS configuration for shutdown like `AutoEndTasks` or `WaitToKillAppTimeout`?

**Comment by MagicAndre1981** [comment] 2024-09-17 05:33
Maybe he has the same issue like #2202 ? @dmex

**Comment by Zeroes1** [comment] 2024-09-17 09:17
I think same https://github.com/winsiderss/systeminformer/issues/2138

**Comment by Dajova** [comment] 2024-09-17 11:44
I dont think so, at least not for shutdown purposes. It just decided to reset itself for no reason after i rebooted the PC after a Windows Update. No idea how to check what happened, tbh, as it was just a normal reboot and not a hard shutdown or cutoff.

**Comment by dmex** [comment] 2024-10-04 14:23
Duplicate of #2138

**Closed by dmex** 2024-10-04 14:23 UTC
