### ISSUE TITLE
Are there any available command-line parameters?

### ISSUE THREAD

**Issue by worm001** [winsiderss/systeminformer#1954] opened 2024-01-06 10:33 UTC
### Description of the feature, modification, idea or suggestion

Is there a command line available? For example, ending a specified process? Its predecessor seemed to be called: processhacker, although it had a command line, the command line to end the process did not seem to load the driver.

**Comment by dmex** [comment] 2024-01-10 19:14
Duplicate of #1953

**Closed by dmex** 2024-01-10 19:14 UTC
Labels: enhancement
