### ISSUE TITLE
Process Hacker 2.39 shut down delay

### ISSUE THREAD

**Issue by not6** [winsiderss/systeminformer#1382] opened 2022-09-22 02:12 UTC
### Brief description of your issue

No, my installation is not corrupted. Yes, I'm 100% sure this is caused by using Process Hacker. I've seen this get reported at least about 5 times before

According to the wait chain in task manager, winlogon seems to be waiting for the DcomLaunch svchost process. Analyzing wait chain for DcomLaunch svchost says it's running fine but I'm pretty sure it's waiting for something else. I could not figure out what it is.
I don't know what other info is required, @ mention me and let me know what else you need.
I'm 100% sure this is caused by Process Hacker, I've used it for a long time and this has only happened when I've used Process Hacker in the current session

### Steps to reproduce (optional)

Seems you only have to open Process Hacker 2.39

### Environment (optional)

```shell
Process Hacker 2.39 stable release
Windows 10 x64 21H2 10.0.19043.2006
only anti-virus software is Windows Defender
```

**Comment by jxy-s** [comment] 2022-09-24 14:49
@not6 could you confirm if this is happening on the latest nightly build or not? Additionally, do you have the kernel driver enabled and loaded when initiating the shutdown?

You can find the latest night build here: https://processhacker.sourceforge.io/nightly.php

**Comment by not6** [comment] 2022-09-25 01:36
I probably should've tried it earlier but I will let you know if I experience the issue with the nightly build. The issue happened at seemingly random, so it might take a while for it to happen if it still occurs.
About the driver, I'm unsure but I don't think it was loaded when the issue was occurring. I'll keep you updated if the issue happens on the nightly build

**Comment by Gaoan88** [comment] 2023-01-05 01:50
try this: cancel "run as administrator"

**Comment by dmex** [comment] 2023-03-15 12:08
Duplicate of #1565

**Closed by dmex** 2023-03-15 12:08 UTC
Labels: bug, needs investigation
