### ISSUE TITLE
24H2 Invalid access to memory location.

### ISSUE THREAD

**Issue by poqdavid** [winsiderss/systeminformer#2196] opened 2024-09-12 23:47 UTC
### Brief description of your issue

I just upgraded to 24H2 and System Informer just randomly crashed with the message saying `0xC0000005 (Invalid access to memory location)`
Dump file: https://drive.google.com/file/d/1P8r1kP9vGyEkvxIuBWVuYeK8E50k4A7k/view

### Steps to reproduce (optional)

I am not sure it was very random wasn't doing anything

### Environment (optional)

```shell
- System Informer version 3.1.24244.0 (41365e9c) x64.
- Windows 11 Pro x64, 24H2, 26100.1742
- Windows Kernel 10.0.26100.1742
```

**Comment by dmex** [comment] 2024-09-28 20:29
Duplicate of #2201

**Closed by dmex** 2024-09-28 20:29 UTC
Labels: bug, needs-triage
