### ISSUE TITLE
Enabling admin rights cripples program almost to a standstill.

### ISSUE THREAD

**Issue by Dajova** [winsiderss/systeminformer#1534] opened 2022-12-12 12:31 UTC
### Brief description of your issue

By just starting up the program as admin (without having starting up as admin checked) makes it so it either just flat out crashes on startup or it runs so slowly as it only moves/updates once per 10-15 sec. Can't even move it because it's that slow.

### Steps to reproduce (optional)

By just trying to launch the program with administrator rights without the checkmark for it enabled triggers this bug. Not sure if there is any other combination aside from that that triggers it.

### Actual behavior (optional)

It works as long as you are somehow able to tick that box, exit and relaunch it, then it runs fine... but not outside of it.

**Comment by dmex** [comment] 2022-12-20 17:56
Duplicate of #1515

**Closed by dmex** 2022-12-20 17:56 UTC
Labels: bug, needs investigation
