### ISSUE TITLE
Unsupported Kernel version

### ISSUE THREAD

**Issue by Hallilogod** [winsiderss/systeminformer#2082] opened 2024-06-01 13:51 UTC
### Brief description of your issue

The windows Kernel version 10.0.19041.4412 is not supported my SystemInformer, please add support for it! Thanks.
![grafik](https://github.com/winsiderss/systeminformer/assets/129677832/25583cf1-9b32-4864-91ed-06c8c1725522)

**Comment by dmex** [comment] 2024-06-02 14:14
Duplicate of #1823

**Closed by dmex** 2024-06-02 14:14 UTC
Labels: bug, needs investigation
