### ISSUE TITLE
Crash on viewing device properties after refreshing devices

### ISSUE THREAD

**Issue by harig** [winsiderss/systeminformer#1865] opened 2023-10-11 08:55 UTC
### Brief description of your issue

Systeminformer 3.0.7256 crashes on viewing properties of a device from Devices tab, after a manual Refresh with context menu item.

### Steps to reproduce (optional)

- Open Devices tab in Systeminformer
- Right click an entry and select Properties from the context menu; Properties dialog is shown.
- Right click and select Refresh 
- Right click and view properties again
- Application crashes, crash dialog shown. 

If the Properties entry is opened after some delay, there is no crash.

### Environment (optional)

```shell
Systeminformer nightly 3.0.7256 on Win10
```

**Comment by jxy-s** [comment] 2023-10-11 14:51
@harig I'm unable to reproduce this on my machines. If possible, could you send us the dump file, please?

**Comment by harig** [comment] 2023-10-12 08:17
Dump uploaded to [sysinfrmr.crash.devices.refresh.props.dmp.gz](https://github.com/winsiderss/systeminformer/files/12878879/sysinfrmr.crash.devices.refresh.props.dmp.gz)

**Comment by jxy-s** [comment] 2023-10-12 15:28
@harig the dump file is lacking sufficient information to identify the root cause. Will you please choose to capture a "full dump" instead. You are also welcome to email me the dump file (johnny.shaw@live.com) instead of uploading it to GitHub.

**Comment by jxy-s** [comment] 2023-10-17 23:51
Should be fixed with: https://github.com/winsiderss/systeminformer/commit/ab71e64680a25dd9598cda2801e07d4f1d78e711

**Comment by jxy-s** [comment] 2023-11-02 00:09
Fix should be available in `3.0.7310`

**Closed by jxy-s** 2023-11-02 00:09 UTC
Labels: bug, waiting on build
