### ISSUE TITLE
AMD Ryzen Threadripper PRO 3995WX 64-Cores [UNKNOWN DEVICE - PLEASE REPORT ON GITHUB]

### ISSUE THREAD

**Issue by StanleyChristmas** [winsiderss/systeminformer#1912] opened 2023-11-28 12:28 UTC
Reporting unknown devices. :)

![image](https://github.com/winsiderss/systeminformer/assets/11148061/5bceb38f-0d99-40e8-907b-83180ca682cc)

**Comment by dmex** [comment] 2023-12-02 07:12
Duplicate of #1558

**Closed by dmex** 2023-12-02 07:12 UTC
