### ISSUE TITLE
Broken graph tray icons since System Informer rename

### ISSUE THREAD

**Issue by xnoreq** [winsiderss/systeminformer#1307] opened 2022-07-17 17:52 UTC
### Brief description of your issue

With the latest commits, all my tray icons like CPU usage, history, etc. are gone.
Interestingly, text tray icons still work.

### Expected behavior (optional)

tray icons show up

### Actual behavior (optional)

no tray icons

### Environment (optional)

```shell
Windows 21H2 19044.1806
```

**Comment by dmex** [comment] 2022-07-17 18:26
Duplicate of #1304

This has been fixed but there hasn't been new nightly builds yet (see #1286) 👍

**Closed by dmex** 2022-07-17 18:26 UTC
Labels: bug, needs investigation

**Comment by xnoreq** [comment] 2022-07-17 22:25
@dmex When was this fixed? I've built c8fcd1a380778db790ec72a0d67cea8d56272b18 and it still doesn't show tray icons.

I've seen #1286 but it's been a month, so I created this bug report.

**Comment by dmex** [comment] 2022-07-18 04:58
> it still doesn't show tray icons

You need to delete/clear the `IconGuids` and `ProcessHacker.ExtendedTools.TrayIconGuids` values from advanced settings.
