### ISSUE TITLE
CTRL+R opens cmd.exe instead of Run Dialog

### ISSUE THREAD

**Issue by MagicAndre1981** [winsiderss/systeminformer#1866] opened 2023-10-11 19:32 UTC
### Brief description of your issue

I use the shortcut CTRL+R to open the Run Dialog, but now this opens CMD.exe

![image](https://github.com/winsiderss/systeminformer/assets/8274816/5272e335-f1d2-45ad-b372-cd3948f409e4)

The Menu still shows CTRL+R as shortcut to open "run":

![image](https://github.com/winsiderss/systeminformer/assets/8274816/6a3951fb-2684-4c19-a84a-cac0af451bdb)

### Steps to reproduce (optional)

press CTRL+R inside SI

### Expected behavior (optional)

it opens the Run Diloag

### Actual behavior (optional)

it starts a CMD.exe

### Environment (optional)

```shell
nightly 3.0.7270 (d44e4d0)
```

**Comment by dmex** [comment] 2023-10-11 19:33
Duplicate of #1859

**Closed by dmex** 2023-10-11 19:33 UTC

**Comment by MagicAndre1981** [comment] 2023-10-11 19:36
ok, I overlooked this 🤦 I'll subscribe to the other issue.

**Comment by MagicAndre1981** [comment] 2023-11-01 21:25
Works now in 3.0.7310 again as expected 👍
