### ISSUE TITLE
Visual glitches in Options dialog for dark mode

### ISSUE THREAD

**Issue by Vasilich** [winsiderss/systeminformer#1502] opened 2022-11-22 07:22 UTC
### Brief description of your issue

Earlier it was said, that dark mode is kinda experimental and any bug report for it will be ignored. So i will try to post here found visual issues for SI then :)
Inconsistent margins between checkboxes and labels:
![image](https://user-images.githubusercontent.com/1168434/203248996-8dfd5b65-839e-44e7-80c7-9bcc01098fd8.png)
![image](https://user-images.githubusercontent.com/1168434/203249155-19066aeb-2951-4a54-b039-22ba2676fc58.png)
Tool status: 
![image](https://user-images.githubusercontent.com/1168434/203249331-0ef2694f-6c8a-4ff3-8342-af606998297f.png)
Updater: 
![image](https://user-images.githubusercontent.com/1168434/203249506-2a594466-a341-4ac1-a36f-88a8e52ad227.png)
UserNotes (shouldn't it be named "User notes" with space between words?) 
![image](https://user-images.githubusercontent.com/1168434/203250129-5626ff55-3f93-411e-a402-1e50a07345f3.png)
NetworkTools (same as above - "Network tools"?)
![image](https://user-images.githubusercontent.com/1168434/203250349-8d2938d5-f7af-48bc-8cb3-19a212868da2.png)

Al on SI 3.0.5553

**Comment by dmex** [comment] 2022-11-22 08:17
> margins between checkboxes and labels

Checkboxes are a known issue. It's caused by DrawTextW with Tahoma fonts. It just needs to be switched to uxtheme drawing whenever we have spare time.

> UserNotes (shouldn't it be named "User notes" with space between words?)
> NetworkTools (same as above - "Network tools"?)

These are the the plugin names/filenames. They're supposed to match so you know what options are for which plugin (and what options are lost when disabling plugins).

**Comment by Vasilich** [comment] 2022-11-23 00:23
> It just needs to be switched to uxtheme drawing whenever we have spare time.

OK, accepted.
Then i just leave this issue opened to rerember that this problem is known and will be fixed somewhen.

**Comment by UhuruNUru** [comment] 2022-11-27 10:26
Only serious issue I'm seeing that needs fixing is
![2022-11-27 10_11_45-Options](https://user-images.githubusercontent.com/4346557/204130120-882a44d7-5efc-411c-8334-21544b704160.png)

If it doesn't appear initially, it maybe toggling the use old colours that triggered this.
Use Old Colors shows in dark mode, but this doesnt, text is turned white, so iit appears to be just the background not changing

**Comment by dmex** [comment] 2022-12-24 06:13
Fixed in latest nightly

**Closed by dmex** 2022-12-24 06:13 UTC
Labels: bug, needs investigation
