### ISSUE TITLE
Systeminformer uses lots of memory in network tab.

### ISSUE THREAD

**Issue by kotenok2000** [winsiderss/systeminformer#2090] opened 2024-06-09 11:15 UTC
### Brief description of your issue

Systeminformer uses lots of memory in network tab.

### Expected behavior (optional)

![image](https://github.com/winsiderss/systeminformer/assets/8822292/34f9d3ac-0aa5-40ea-bbd8-0d3c74dd4902)

### Actual behavior (optional)

![image](https://github.com/winsiderss/systeminformer/assets/8822292/7b9260a2-684b-4005-9171-9bc338004c76)

### Environment (optional)

```shell
system informer version 3.0.7741

Microsoft Windows [Version 10.0.22631.3593]
```

**Comment by kotenok2000** [comment] 2024-06-21 13:21
Turns out it could happen not only in network tab
![image](https://github.com/winsiderss/systeminformer/assets/8822292/82b34d35-9efc-47a3-bd6a-94f7c390ee0e)

**Comment by dmex** [comment] 2024-08-04 07:04
Duplicate of #1933

**Closed by dmex** 2024-08-04 07:04 UTC
Labels: needs investigation
