### ISSUE TITLE
Virus scanning doesn't work

### ISSUE THREAD

**Issue by SanderBouwhuis** [winsiderss/systeminformer#2255] opened 2024-10-27 11:53 UTC
### Brief description of your issue

I have virus scanning on, but virus scanning doesn't work.

### Steps to reproduce (optional)

1. Enable virus scanning with VirusTotal:
![2024-10-27 12-47-56 637x558 Options](https://github.com/user-attachments/assets/454aedc1-b1ab-4f9f-897d-637fa1c3a8fb)

2. Virus scanning doesn't work
![2024-10-27 12-48-43 1573x897 System_Informer_ HOMEBouwhuis _(Administrator)](https://github.com/user-attachments/assets/f3cc3a10-22da-474f-9594-a29880b0b2ec)

3. Try to do it manually:
![2024-10-27 12-49-09 1573x897 System_Informer_ HOMEBouwhuis _(Administrator)](https://github.com/user-attachments/assets/7e080a5f-125b-4a23-b306-2b14405adeec)

4. This also doesn't work
![2024-10-27 12-49-51 402x149 Uploading_SystemInformer exe](https://github.com/user-attachments/assets/958e9d0a-ef76-4604-a999-d0f3758a8543)

### Expected behavior (optional)

I expect the feature to work, i.e., that it scans for virii

### Actual behavior (optional)

It doesn't work, no scans are performed

### Environment (optional)

```shell
Windows 10 Pro x64
System Informer 3.1.24298.0 Release
OBJECT INFORMATION
PhObjectTypeObject: 22 objects
PhStringType: 5583 objects
PhBytesType: 0 objects
PhListType: 303 objects
PhPointerListType: 128 objects
PhHashtableType: 24 objects
PhFileStreamType: 0 objects
PhSymbolProviderType: 0 objects
PhProcessItemType: 239 objects
PhServiceItemType: 776 objects
PhNetworkItemType: 0 objects
PhModuleProviderType: 0 objects
PhModuleItemType: 0 objects
PhThreadProviderType: 0 objects
PhThreadItemType: 0 objects
PhHandleProviderType: 0 objects
PhHandleItemType: 0 objects
PhMemoryItemType: 0 objects
PhImageListItemType: 423 objects
```

**Comment by dmex** [comment] 2024-10-28 00:45
Duplicate of #1783

**Closed by dmex** 2024-10-28 00:45 UTC
Labels: needs-triage
