### ISSUE TITLE
"Unable to query affinity" the COMEBACK

### ISSUE THREAD

**Issue by Framexdd** [winsiderss/systeminformer#1317] opened 2022-07-25 07:28 UTC
### Brief description of your issue

Biggest comeback in history.

Last time i had an issue with setting affinities on the newer versions of nightly #1299 
It got fixed but the error still persist whenever i try to save affinity from process/command line (Happens on W7 sp1, didnt check on w10)
![Untitled](https://user-images.githubusercontent.com/89939481/180721471-5c0f052c-6088-41fb-a1af-758f59aacbf4.png)

### Steps to reproduce (optional)

Be alive. And have modded usb drivers to allow u to use w7 on new hardware

**Comment by jxy-s** [comment] 2022-07-26 02:38
@Framexdd this should be fixed for you with the above commit.

`UserNotes` I think needs updated in general to be group-aware (cc: @dmex). I didn't look too closely tho.

**Comment by Framexdd** [comment] 2022-07-26 10:29
@jxy-s No luck :/
Still get the same error

**Comment by jxy-s** [comment] 2022-07-26 15:06
Okay, I'll take another look.

**Comment by jxy-s** [comment] 2022-07-26 16:16
I looked at the `6.1.7601.17514` kernel in IDA and `ProcessAffinityMask` is not supported on `NtQueryInformationProcess`. For first our documentation is wrong on this information class. Second I'm going to fix our library to correctly choose the right path based on the OS version. I'm not yet confident precisely where this info class started being available for query. I have a patch that should fix it but I want to make sure our lib and documentation is correct to avoid this confusion moving forward 😄.

I'll look into it further this evening. Thanks for your patience @Framexdd.

**Comment by dmex** [comment] 2022-07-26 23:37
Duplicate of #1299

**Closed by dmex** 2022-07-26 23:37 UTC
Labels: bug, IN PROGRESS
