### ISSUE TITLE
System Informer if started as a task upon logon causes system lag in both browsers and Explorer

### ISSUE THREAD

**Issue by Almighty188** [winsiderss/systeminformer#1721] opened 2023-05-07 06:21 UTC
### Brief description of your issue

I discovered this by accident as basically I am running System Informer as admin with the SystemInformer.exe in the amd64 folder after extracting the zip file which works fine.  But I wanted to save time and just have it launch when I login so I created a task to run it upon logging in instead of having to open File Explorer, browse to C:\Users\vince\Downloads\systeminformer-3.0.6550-bin\amd64\ before right clicking on SystemInformer.exe and run as Admin.

However, when I run it as a task for any user upon login, it seems to create major lags with the browser as well as explorer, file explorer.  Issue is not there when I disable the task and then run SystemInformer.exe in the amd64 folder manually.

I am running System Informer v3.0.6550 Nightly Build.  

### Steps to reproduce (optional)

1) Create task which I named "System Informer"
2) Here are the properties screens:
https://user-images.githubusercontent.com/78993393/236660832-11cf5744-fd84-4acd-bd43-6633695c0f3d.png
https://user-images.githubusercontent.com/78993393/236660845-77b74817-1445-4541-83aa-79171f9259ae.png
https://user-images.githubusercontent.com/78993393/236660860-3f674110-0d45-40ba-bbec-8ab1cea76072.png
https://user-images.githubusercontent.com/78993393/236660890-7a80156e-aaa9-4052-bb6c-d7276e699019.png
For the above as it didn't show everything in the screenshot:
Program/script: C:\Users\vince\Downloads\systeminformer-3.0.6550-bin\amd64\SystemInformer.exe
Start in (optional): C:\Users\vince\Downloads\systeminformer-3.0.6550-bin\amd64\
https://user-images.githubusercontent.com/78993393/236660935-da6ea1e4-cde6-40c6-a8be-0f324301d4f7.png
https://user-images.githubusercontent.com/78993393/236660953-7e34f50d-fc15-452c-9aa2-cfb06975b010.png
https://user-images.githubusercontent.com/78993393/236660970-0fd8fc42-e403-4347-8bb4-a8aabe224d81.png

Then basically login to Windows after system starts up

### Expected behavior (optional)

It works normally without the issues mentioned in Actual Behavior.  If I disable the task from starting and manually goto the folder and run SystemInformer.exe from amd64 as Admin, it works fine.  Not sure if the issue is caused by System Informer running too early because it runs in login versus the manual method of running it a few minutes after logging into Windows.  

### Actual behavior (optional)

It is creating major lags in the following area:
1) File Explorer - files written do not show up on the screen under atleast a minute later as it will cause a spinning circle to wait
2) The Web Browsers whether it be Firefox, Google Chrome, Microsoft Edge, Brave
3) Desktop will take some time to be available as it will have a spinning cursor which can take from one minute up to five minutes
4) Opening apps also creates delays 
5) Using TechSmith SnagIt, when I take a screenshot - instead of how it instantly loads in the SnagIt Editor when SystemInformer.exe is run manually instead of as a task - it takes probably 30 seconds or more before the screenshot is loaded into the Editor, same with when trying to save the image as a file, it will also take atleast 30 seconds or more instead of within 1-2 seconds.

Closing SystemInformer.exe and starting the SystemInformer.exe in amd64 did not fix the problem.
 
### Environment (optional)

```shell
System Informer Nightly Build v3.0.6550
Windows 11 Professional Edition x64 22H2 Builds 22624.1680 and 22624.1690 Beta Insiders Channel

```

**Comment by dmex** [comment] 2023-05-08 13:44
> Not sure if the issue is caused by System Informer running too early because it runs in login

No. I've never seen issues like those during startup. In fact you can execute System Informer in pre-boot environments like WinPE before logon or even during Windows setup while installing the OS. These environments have zero support for running anything but they're able to run System Informer.

Start the Windows setup or WinPE from USB and press SHIFT+F10 to open a console then execute systeminformer.exe to monitor pre-boot environments: https://i.imgur.com/9VNG10g.png

> Closing SystemInformer.exe and starting the SystemInformer.exe in amd64 did not fix the problem.

If exiting SystemInformer doesn't fix the issue then some other program is responsible?

> It is creating major lags in the following area:

System Informer doesn't interact with those programs.

A simple method to find the program responsible is start killing everything - terminate every program that isn't from Microsoft one by one. When the lag suddenly stops then the last program you just killed was responsible, reboot and try killing that program again to confirm it's responsible.

**Comment by dmex** [comment] 2023-05-18 05:13
Duplicate of #1515

We found third parties ddosing the kernel driver with thousands of hook attempts when their DLLs are blocked. The next release will include some targeted mitigations to prevent the spam.

**Closed by dmex** 2023-05-18 05:13 UTC
Labels: bug, needs investigation
