### ISSUE TITLE
Systeminformer crashes on Windows 11 Pro Insider Preview 25931.1010

### ISSUE THREAD

**Issue by KastriotH** [winsiderss/systeminformer#1827] opened 2023-08-24 04:10 UTC
Hi, i am on canary insider channel, before that i was on beta and i didn't had issues and now it's crashing, i disabled kernel driver ofc but still nothing i will send you crash report.

Faulting application name: SystemInformer.exe, version: 3.0.11333.6806, time stamp: 0xf88e4c72
Faulting module name: ntdll.dll, version: 10.0.25931.1000, time stamp: 0x1cab777a
Exception code: 0xc0000409
Fault offset: 0x00000000000c0ecb
Faulting process id: 0x0x4E34
Faulting application start time: 0x0x1D9D58A44243AF6
Faulting application path: C:\Program Files\SystemInformer\SystemInformer.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 62f23252-0032-4592-927e-fac17bd0cc19
Faulting package full name: 
Faulting package-relative application ID: 

If you need anything else tell me.

**Comment by dmex** [comment] 2023-08-24 08:47
Duplicate of #1787

**Closed by dmex** 2023-08-24 08:47 UTC
