### ISSUE TITLE
Strings

### ISSUE THREAD

**Issue by KurexV0** [winsiderss/systeminformer#1769] opened 2023-06-22 11:21 UTC
Hey i wanted to ask if there is a way to delete strings ?

**Comment by imjusthereforprocesshacker** [comment] 2023-08-28 04:03
> Hey i wanted to ask if there is a way to delete strings ?

Ever find out how?

**Comment by dmex** [comment] 2023-09-05 17:00
Duplicate of #1831

**Closed by dmex** 2023-09-05 17:00 UTC
