### ISSUE TITLE
geoip updates

### ISSUE THREAD

**Issue by marcobelmonte** [winsiderss/systeminformer#2069] opened 2024-05-19 09:33 UTC
### Brief description of your issue

When I try and enter a valid and newly generated maxmind geoip license key and hit update I get an access denied error. The same key can be used to download updates from other programs.

### Steps to reproduce (optional)

![image](https://github.com/winsiderss/systeminformer/assets/4238826/6f85429a-3a5a-42d0-8b4d-1b39dd77df0f)

### Expected behavior (optional)

Expecting the geoip database get downloaded so it is not using the free database but the latest commerical one provided at cost by Maxmind.

**Comment by dmex** [comment] 2024-05-19 10:46
> Expecting the geoip database get downloaded so it is not using the free database but the latest commerical one provided at cost by Maxmind

Looks like the API was updated and now requires a signed URL specific to each license and Account ID before it can download database updates.

You'll have to follow the instructions here and download the database manually with curl (included with Windows 10 and 11)

https://dev.maxmind.com/geoip/updating-databases#directly-downloading-databases

![image](https://github.com/winsiderss/systeminformer/assets/1306177/03cc1683-e589-438d-9eee-2fe5043ea54d)

![image](https://github.com/winsiderss/systeminformer/assets/1306177/80ffa55d-b26e-40ed-ae83-d14f280ed3bf)

Download the databse with curl and extract the mmdb file into `%appdata%\SystemInformer\` and for the moment you'll have to name the file `GeoLite2-Country.mmdb` until we update the mmdb updater.

**Comment by marcobelmonte** [comment] 2024-05-21 10:35
Thank you sir - that worked and will get me by until things get synced up in System Informer's functionality. Much appreciated for all the work you guys do!

**Comment by Almighty188** [comment] 2024-06-08 01:08
My GeoIP database update works fine even now in 3.0.7660-canary, only broken in 3.1.7741-canary.

**Comment by dmex** [comment] 2024-06-08 17:58
@Almighty188 

You need to generate a new key since the format changed. We don't support the legacy format going forward.

Changes to MaxMind License Keys: https://dev.maxmind.com/geoip/release-notes/2023#changes-to-maxmind-license-keys

**Comment by Almighty188** [comment] 2024-06-08 18:10
> @Almighty188
> 
> You need to generate a new key since the format changed. We don't support the legacy format going forward.
> 
> Changes to MaxMind License Keys: https://dev.maxmind.com/geoip/release-notes/2023#changes-to-maxmind-license-keys

My key works fine.  The issue is not the key but if you look at the error message from 3.1.77741, it says ID "or" key not ID "and" key which is what needs to be fixed as it is saying it needs one or the other and not both.  With both, it works fine.

![image](https://github.com/winsiderss/systeminformer/assets/78993393/2eed2d95-9795-4d7f-92c5-d7f87bffd27e)

**Comment by Almighty188** [comment] 2024-06-08 22:09
> Thank you sir - that worked and will get me by until things get synced up in System Informer's functionality. Much appreciated for all the work you guys do!

What's strange here is my key which is a v3.1.1 key and not a legacy key from November 29, 2022 still works fine and I can download successfully even as of this moment.  3.1.7741 requires adding in the ID before it will allow the download but it is still the same key used.

**Comment by Almighty188** [comment] 2024-06-10 04:20
Appears that System Informer v3.1.7741 is also downloading Country instead of City.  

<img width="477" alt="image" src="https://github.com/winsiderss/systeminformer/assets/78993393/22dc08ad-ce37-4e66-967e-8f444cad5b7a">

**Comment by dmex** [comment] 2024-07-06 07:35
Resolved in the latest version

**Closed by dmex** 2024-07-06 07:35 UTC
Labels: enhancement

**Comment by marcobelmonte** [comment] 2024-07-06 23:57
Not sure if I can add a comment after this has been closed but just wanted to say that I generated a new key and was able to download the GeoIP City Database no problem. Thanks!

![image](https://github.com/winsiderss/systeminformer/assets/4238826/c05a825c-5a84-40b4-af09-74a6c5486fac)

![image](https://github.com/winsiderss/systeminformer/assets/4238826/3fd617bc-8ac9-457e-8eab-2533c3cc6d6f)

Again, thanks so much for your work on this unbelievably useful software! 

![praying-caprisun](https://github.com/winsiderss/systeminformer/assets/4238826/8befebf3-ce41-4736-bf02-0289bb5f5d60)
