### ISSUE TITLE
peview crash

### ISSUE THREAD

**Issue by pluto1313** [winsiderss/systeminformer#1907] opened 2023-11-24 04:46 UTC
1. Run peview.exe
2. Choose SystemInformer.exe
3. Click "Exports", then peview.exe crash
![PEVIEW](https://github.com/winsiderss/systeminformer/assets/151900006/85f0fa38-a8ae-4d18-a138-d207fce697d3)

ver: 3.0.11860.7333, amd64
win ver: Win10 Pro 19045.3693 x64

**Comment by dmex** [comment] 2023-12-26 21:58
Unable to reproduce

**Comment by hg421** [comment] 2023-12-28 21:06
I hit this issue today with the latest version (although not looking at SystemInformer.exe, but some random DLL from system32). The crash (0xC0000005) would happen each time after opening that DLL and clicking on "Exports".
However I can not reproduce it anymore now, after rebooting the machine.

But I checked the location of the crash: Apparently in this line, the first argument to `PhEqualString` was NULL.
https://github.com/winsiderss/systeminformer/blob/755b5537586967eef53c203404db9301c8f5750d/tools/peview/expprp.c#L325C115-L325C115

**Comment by jxy-s** [comment] 2024-02-10 21:48
fixed by: https://github.com/winsiderss/systeminformer/commit/8df1f0f13a7fe32ab03339c9ecab5beeae0591b8

**Closed** 2024-02-14 06:07 UTC
Labels: bug, waiting on build
