### ISSUE TITLE
Kernel-mode driver can render System Informer unusable

### ISSUE THREAD

**Issue by ImportTaste** [winsiderss/systeminformer#1708] opened 2023-04-29 22:35 UTC
## What led up to me submitting this issue:

I was intrigued by the kernel-mode driver features described here: https://github.com/winsiderss/systeminformer/discussions/1375#discussioncomment-5749115

But after enaabling it, it made System Informer completely unusable. It took a few minutes just for it to allow me to press the Options button, several minutes for it to load, and then when I unchecked the option, the options window went blank and I had no idea if it registered so I waited even longer, but it remained blank. Thankfully, after closing it out and then terminating System Informer (I had to use `Stop-Process -Force` in PowerShell), it came back up with the kernel-mode driver disabled.

This is likely due to the system's fairly old CPU (an i5-6500) and the 1s refresh interval. I'm also using theme support, so that might've been a factor when it came to the GUI being particularly unresponsive when it came to trying to turn the option back off.

## Suggestions:

Efficiency improvements to the kernel-mode driver are a given, but I have no idea if it's possible to make it efficient enough for this to not be an issue.

There should at least be a warning that the option is far more CPU-intensive than running System Informer without it.

Additionally, perhaps System Informer should be able to recognize if it's maxing out a core and start throttling its own refresh interval? The window title could be changed to reflect this, appending something like `(Throttled; Interval: 10s)`.

I think the best solution of all, though, would be to make kernel-mode System Informer a separate executable and have it be launched from the toolbar's Tools menu, and while it would use the same configuration files, it would have a separate refresh interval value that defaults to 10s. In tandem, removing the kernel-mode driver option from the Options window. Maybe there could be a new option that only appears when "Show advanced options" is enabled to have the default Task Manager be the kernel-mode System Informer executable.

**Comment by jxy-s** [comment] 2023-04-30 00:25
@ImportTaste this is a duplicate of: https://github.com/winsiderss/systeminformer/issues/1515

**Closed by jxy-s** 2023-04-30 00:25 UTC

**Comment by jxy-s** [comment] 2023-04-30 00:27
@ImportTaste please update the other issue with any information you feel necessary. The issue happens with and without the kernel driver enabled. It's been a little tricky to track down. I suggest the following:

1. back up your settings and configuration in `%appdata%\SystemInformer`
2. delete that directory
3. run System Informer with the default settings and then enable _only_ the kernel driver setting
4. does the issue still reproduce?

Please update the other issue with this information.

Finally, feel free to email me your settings and configuration so I can try to reproduce what you're seeing.

**Comment by jxy-s** [comment] 2023-04-30 00:33
FYI, one user had success with rebuilding their settings file, so you might find success there: https://github.com/winsiderss/systeminformer/issues/1515#issuecomment-1341226383

Also, it might be worth trying `KphDisableImageLoadProtection` (there could be some security software interfering with this mitigation) - you will have to unload and reload the kernel driver to apply that setting.

**Comment by jxy-s** [comment] 2023-04-30 17:21
FYI, @ImportTaste - in case you aren't following that other issue yet, I posted some instructions to capture a trace log of the driver. It would be super helpful if you could do that for us and attach/email the log file: https://github.com/winsiderss/systeminformer/issues/1515#issuecomment-1529085306

Thank
