### ISSUE TITLE
SystemInformer crash

### ISSUE THREAD

**Issue by MarekKnapek** [winsiderss/systeminformer#1623] opened 2023-02-28 19:18 UTC
Version 3.0.6215 for x64. In main window, in process list, I pressed enter key on some process to display per-process properties, then I pressed ctrl+tab (maybe I pressed and kept holding) to switch to another tab, then crash happened. I selected normal dump option. Dump file is attached. https://1drv.ms/u/s!Apd3fBFNSoM6gXTlr7siqld4TW3E

**Comment by as-muncher** [comment] 2023-02-28 21:43
I also have a crash dump, minidump.
[SystemInformer_QJRFKOBTXJXKKTQ_DumpFile.zip](https://github.com/winsiderss/systeminformer/files/10855006/SystemInformer_QJRFKOBTXJXKKTQ_DumpFile.zip)

**Comment by jxy-s** [comment] 2023-02-28 21:52
```
0:013> k
  *** Stack trace for last set context - .thread/.cxr resets it
 # Child-SP          RetAddr               Call Site
00 (Inline Function) --------`--------     SystemInformer!PhGetProcessBasicInformation+0x12 [phlib\include\phnativeinl.h @ 22] 
01 0000005a`4eefe9b0 00007ff6`2be87718     SystemInformer!PhpFlushProcessPropSheetWaitContextData+0x9c [SystemInformer\procprp.c @ 579] 
02 0000005a`4eefeb00 00007ffa`aba60089     SystemInformer!PhpPropSheetWndProc+0x338 [SystemInformer\procprp.c @ 313] 
03 0000005a`4eefecd0 00007ffa`aba5fa02     user32!UserCallWinProcCheckWow+0x319
04 0000005a`4eefee60 00007ffa`aba5a30b     user32!DispatchMessageWorker+0x1d2
05 0000005a`4eefeee0 00007ffa`95d17333     user32!IsDialogMessageW+0x12b
06 0000005a`4eefef40 00007ffa`95db68c8     comctl32!Prop_IsDialogMessage+0x4b
07 0000005a`4eefef80 00007ffa`aba5b37b     comctl32!PropSheetDlgProc+0x9ea58
08 0000005a`4eeff080 00007ffa`aba5babb     user32!UserCallDlgProcCheckWow+0x14b
09 0000005a`4eeff160 00007ffa`aba5b9c6     user32!DefDlgProcWorker+0xcb
0a 0000005a`4eeff220 00007ffa`aba60089     user32!DefDlgProcW+0x36
0b 0000005a`4eeff260 00007ffa`aba5fcfe     user32!UserCallWinProcCheckWow+0x319
0c 0000005a`4eeff3f0 00007ff6`2be87754     user32!CallWindowProcW+0x8e
0d 0000005a`4eeff440 00007ffa`aba60089     SystemInformer!PhpPropSheetWndProc+0x374 [SystemInformer\procprp.c @ 319] 
0e 0000005a`4eeff610 00007ffa`aba5f5ac     user32!UserCallWinProcCheckWow+0x319
0f 0000005a`4eeff7a0 00007ffa`aba5f30f     user32!SendMessageWorker+0x23c
10 0000005a`4eeff840 00007ff6`2bf14b7c     user32!SendMessageW+0x10f
11 0000005a`4eeff8a0 00007ff6`2be88b48     SystemInformer!PhModalPropertySheet+0x17c [phlib\guisup.c @ 1343] 
12 0000005a`4eeffb40 00007ff6`2bf06f6b     SystemInformer!PhpProcessPropertiesThreadStart+0x6a8 [SystemInformer\procprp.c @ 928] 
13 0000005a`4eeffe10 00007ffa`ac4e4de0     SystemInformer!PhpBaseThreadStart+0x6b [phlib\basesup.c @ 200] 
14 0000005a`4eeffe50 00007ffa`acc9e40b     kernel32!BaseThreadInitThunk+0x10
15 0000005a`4eeffe80 00000000`00000000     ntdll!RtlUserThreadStart+0x2b
```

Looks like a duplicate of this: https://github.com/winsiderss/systeminformer/issues/1614

**Comment by as-muncher** [comment] 2023-02-28 21:53
@jxy-s ah, okay, thanks.  I couldn't tell.

**Comment by MarekKnapek** [comment] 2023-02-28 21:56
I confirm that both dumps have different call stacks.

**Closed** 2023-03-10 13:11 UTC
