### ISSUE TITLE
Smartscreen persistently blocks System Informer (Win10 pro) PITA

### ISSUE THREAD

**Issue by methuzla** [winsiderss/systeminformer#1716] opened 2023-05-05 21:24 UTC
SmartScreen (Win10pro,64b)is blocking valid download, 
even when permitted exception in Defender (after reboot, even)
and external process marked as ok (during brief time before it is deleted)
even on re-try.

The standard fixes are just NOT working now.
Smartscreen marks and deletes installer download,  falsely tells it is a trojan. 
 despite normal actions to allow it, 
 despite registering exception in defender
 despite accepting external download
 virustotal.com returns zero for the download:
https://github.com/winsiderss/si-builds/releases/download/3.0.6550/systeminformer-3.0.6550-setup.exe

this app is a well-known type of improved task manager:
https://www.systeminformer.com/nightly.php

I have reported to MS as not a problem (I forget where that opportunity arises).

workaround? I suppose I can suspend smartscreen, 
and see if defender kills it anyway once installed
which it did before (hence need to reinstall)
but at that time it was not registered as exception.

Reported to windows feedback hub.

**Comment by dmex** [comment] 2023-05-05 22:58
Duplicate of #1668

**Closed by dmex** 2023-05-05 22:58 UTC
