### ISSUE TITLE
Crash in Windows view

### ISSUE THREAD

**Issue by MarekKnapek** [winsiderss/systeminformer#1673] opened 2023-04-04 02:00 UTC
### Brief description of your issue

System Informer crashes.

### Steps to reproduce (optional)

 - Main menu.
 - View.
 - Windows.
 - Click on list view's "Modules" header.
 - Crash.

### Expected behavior (optional)

No crash.

### Environment (optional)

```shell
System Informer latest nightly.
```

**Comment by dmex** [comment] 2023-04-04 02:52
Duplicate of #1674

**Closed by dmex** 2023-04-04 02:52 UTC
Labels: bug
