### ISSUE TITLE
Wrong text color in menu in dark mode

### ISSUE THREAD

**Issue by egortech** [winsiderss/systeminformer#1919] opened 2023-12-02 08:08 UTC
### Brief description of your issue

When enabled theme supports application menu and context menu shows incorrectly: no text displayed on it until menu item is not selected:

<img width="233" alt="image" src="https://github.com/winsiderss/systeminformer/assets/13813684/6383090c-110d-442c-aec4-875ee0a5214d">

### Steps to reproduce (optional)

Enable theme support with dark system theme on Windows 11 and open application menu

### Expected behavior (optional)

Application menu and context menu should render correctly when theme support enabled.

### Actual behavior (optional)

Application menu and context menu render incorrectly when theme support enabled: text is not visible

### Environment (optional)

```shell
System Informer 3.0.7333
Windows 11 Pro Insider Preview 23595.1001
```

**Comment by dmex** [comment] 2023-12-05 12:28
Try changing the `EnableThemeAcrylicSupport` setting to 0

**Comment by egortech** [comment] 2023-12-05 20:27
Yes, it works. Thank you!

**Comment by dmex** [comment] 2023-12-26 21:55
Duplicate of #1695

**Closed by dmex** 2023-12-26 21:55 UTC
Labels: bug, needs investigation
